---

  - name: install packages
    apt: name={{ item }} state=present
    with_items:
        - nginx
        - docker.io
        - python-pip

  - name: pull wp docker image
    shell: docker pull wordpress

  - name: Populate proxypass file in nginx
    template: src=nginxdefault.j2 dest=/etc/nginx/sites-available/default
    register: fileupdated

  - name: Populate wp execution file
    template: src=execution.j2 dest=/tmp/execut.sh

  - name: restart nginx
    service: name=nginx state=restarted
    when: fileupdated.changed

  - name: execute shell to set up wp
    shell: bash -x /tmp/execut.sh

